### ISSUE TITLE
i am a noob

### ISSUE THREAD

**Issue by suvidh** [endiliey/cs50#1]
just wanted to ask what does the last two line of code mean?

**Comment by endiliey** [comment]
Which two lines of code?

**Comment by suvidh** [comment]
if __name__ == "__main__":
    main()

**Comment by suvidh** [comment]
if __name__ == "__main__":
    main()

**Comment by endiliey** [comment]
When the Python interpreter reads a source file, it executes all of the code found in it.

Before executing the code, it will define a few special variables. For example, if the python interpreter is running that module (the source file) as the main program, it sets the special __name__variable to have a value "__main__". If this file is being imported from another module, __name__will be set to the module's name.

In the case of your script, let's assume that it's executing as the main function, e.g. you said something like

python threading_example.py

on the command line. After setting up the special variables, it will execute the import statement and load those modules. It will then evaluate thedef block, creating a function object and creating a variable called myfunction that points to the function object. It will then read the if statement and see that __name__ does equal "__main__", so it will execute the block shown there.

One of the reasons for doing this is that sometimes you write a module (a .py file) where it can be executed directly. Alternatively, it can also be imported and used in another module. By doing the main check, you can have that code only execute when you want to run the module as a program and not have it execute when someone just wants to import your module and call your functions themselves.

**Comment by suvidh** [comment]
thanks a lot!!!
